Repository jasmin-lang/jasmin, pull requests merged in 2023-02, with the labels that each got.

#339 Remove some unnecessary @s and implicit parameters
  proofs/compiler/allocation_proof.v
  proofs/compiler/array_copy_proof.v
  proofs/compiler/array_expansion_proof.v
  proofs/compiler/array_init_proof.v
  proofs/compiler/constant_prop_proof.v
  proofs/compiler/dead_calls_proof.v
  proofs/compiler/dead_code_proof.v
  proofs/compiler/inline_proof.v
  proofs/compiler/linearization_proof.v
  proofs/compiler/makeReferenceArguments_proof.v
  proofs/compiler/merge_varmaps_proof.v
  proofs/compiler/propagate_inline_proof.v
  proofs/compiler/remove_globals_proof.v
  proofs/compiler/stack_alloc_proof_2.v
  proofs/compiler/tunneling_proof.v
  proofs/compiler/unrolling_proof.v
  proofs/compiler/x86_lowering_proof.v
  proofs/compiler/x86_params_proof.v
  proofs/lang/expr_facts.v
  proofs/lang/psem.v
  proofs/lang/psem_facts.v
  proofs/lang/psem_of_sem_proof.v
  proofs/lang/sem_one_varmap_facts.v
Labels: refactoring

#337 default.nix: mathcomp 1.12 → 1.15
  scripts/coqword.nix
Labels: CI

#341 Compiler: perform two rounds of range splitting
  CHANGELOG.md
  compiler/tests/success/bug_340.jazz
  proofs/compiler/compiler.v
  proofs/compiler/compiler_proof.v
Labels: enhancement

#347 Modularize CLI errors
  compiler/jasmin.mlpack.in
  compiler/src/CLI_errors.ml
  compiler/src/CLI_errors.mli
  compiler/src/main_compiler.ml
  compiler/src/utils.ml
  compiler/src/utils.mli
  default.nix
Labels: enhancement, ocaml

#344 default.nix: use Coq 8.16
  default.nix
Labels: CI

#352 [CI] EasyCrypt: build with Dune 3
  scripts/easycrypt.nix
Labels: CI, nix

#343 Checksafety: soundly handle ArrayInit
  CHANGELOG.md
  compiler/safety/fail/array_init.jazz
  compiler/safety/success/parr_init.jazz
  compiler/src/safety/safetyAbsExpr.ml
  compiler/src/safety/safetyAbsExpr.mli
  compiler/src/safety/safetyInterpreter.ml
Labels: bug, safety-checking

#353 Remove is_regx from lowering-params
  compiler/src/main_compiler.ml
  proofs/compiler/arch_params.v
  proofs/compiler/arch_params_proof.v
  proofs/compiler/arm_params.v
  proofs/compiler/arm_params_proof.v
  proofs/compiler/compiler.v
  proofs/compiler/compiler_proof.v
  proofs/compiler/x86_lowering.v
  proofs/compiler/x86_lowering_proof.v
Labels: refactoring

#355 ARM: mark the export functions as .global
  compiler/src/pp_arm_m4.ml
Labels: arm
