Repository jasmin-lang/jasmin, pull requests merged in 2023-05, with the labels that each got.

#416 ARM lowering: assignment of large (truncated) integers
  compiler/tests/success/arm-m4/bug_375.jazz
  proofs/compiler/arm_lowering.v
  proofs/compiler/arm_lowering_proof.v
Labels: bug, arm

#422 Register allocation: check bank for forced registers
  CHANGELOG.md
  compiler/src/regalloc.ml
  compiler/tests/fail/register_allocation/x86-64/bug_421.jazz
  compiler/tests/success/x86-64/cqo.jazz
Labels: bug, register-allocation

#434 Fix typos, remove dead code in runtest
  compiler/scripts/runtest
Labels: enhancement, CI

#442 x86: fix semantics of VPERMD, VPMADDWD, & VPMADDUBSW
  CHANGELOG.md
  proofs/lang/word.v
Labels: bug, semantics

#453 Check ARM modified immediate constants before printing (and some fixes)
  compiler/src/pp_arm_m4.ml
  compiler/tests/fail/arm-m4/adc_imm_too_large.jazz
  compiler/tests/fail/arm-m4/add_imm_too_large.jazz
  compiler/tests/fail/arm-m4/addw_set_flags.jazz
  compiler/tests/fail/arm-m4/and_imm_shifted.jazz
  compiler/tests/fail/arm-m4/and_imm_too_large.jazz
  compiler/tests/fail/arm-m4/bic_imm_shifted.jazz
  compiler/tests/fail/arm-m4/bic_imm_too_large.jazz
  compiler/tests/fail/arm-m4/cmp_imm_too_large.jazz
  compiler/tests/fail/arm-m4/eor_imm_shifted.jazz
  compiler/tests/fail/arm-m4/eor_imm_too_large.jazz
  compiler/tests/fail/arm-m4/mov_imm_shifted.jazz
  compiler/tests/fail/arm-m4/mov_imm_too_large.jazz
  compiler/tests/fail/arm-m4/mov_shiftedw_set_flags.jazz
  compiler/tests/fail/arm-m4/movw_set_flags.jazz
  compiler/tests/fail/arm-m4/mvn_imm_shifted.jazz
  compiler/tests/fail/arm-m4/mvn_imm_too_large.jazz
  compiler/tests/fail/arm-m4/orr_imm_shifted.jazz
  compiler/tests/fail/arm-m4/orr_imm_too_large.jazz
  compiler/tests/fail/arm-m4/rsb_imm_too_large.jazz
  compiler/tests/fail/arm-m4/sub_imm_too_large.jazz
  compiler/tests/fail/arm-m4/subw_set_flags.jazz
  compiler/tests/fail/arm-m4/tst_imm_shifted.jazz
  compiler/tests/fail/arm-m4/tst_imm_too_large.jazz
  compiler/tests/success/arm-m4/add.jazz
  compiler/tests/success/arm-m4/and.jazz
  compiler/tests/success/arm-m4/eor.jazz
  compiler/tests/success/arm-m4/intrinsic_adc.jazz
  compiler/tests/success/arm-m4/intrinsic_add.jazz
  compiler/tests/success/arm-m4/intrinsic_and.jazz
  compiler/tests/success/arm-m4/intrinsic_bic.jazz
  compiler/tests/success/arm-m4/intrinsic_cmp.jazz
  compiler/tests/success/arm-m4/intrinsic_eor.jazz
  compiler/tests/success/arm-m4/intrinsic_mov.jazz
  compiler/tests/success/arm-m4/intrinsic_mvn.jazz
  compiler/tests/success/arm-m4/intrinsic_orr.jazz
  compiler/tests/success/arm-m4/intrinsic_rsb.jazz
  compiler/tests/success/arm-m4/intrinsic_sub.jazz
  compiler/tests/success/arm-m4/intrinsic_tst.jazz
  compiler/tests/success/arm-m4/mov.jazz
  compiler/tests/success/arm-m4/mvn.jazz
  compiler/tests/success/arm-m4/orr.jazz
  compiler/tests/success/arm-m4/sub.jazz
  proofs/_CoqProject
  proofs/compiler/arm_decl.v
  proofs/compiler/arm_facts.v
  proofs/compiler/arm_lowering.v
  proofs/compiler/arm_lowering_proof.v
  proofs/compiler/arm_params.v
  proofs/compiler/arm_params_proof.v
  proofs/lang/word.v
Labels: arm

#458 eclib: do not attempt to model the parity flag
  eclib/JWord.ec
Labels: bug, EasyCrypt

#451 x86: fix semantics of SHR, RCL, and RCR
  CHANGELOG.md
  eclib/JWord.ec
  proofs/compiler/x86_instr_decl.v
Labels: bug, EasyCrypt, semantics

#459 ARM: fix description of MOV
  compiler/tests/success/arm-m4/add.jazz
  compiler/tests/success/arm-m4/and.jazz
  compiler/tests/success/arm-m4/asr.jazz
  compiler/tests/success/arm-m4/call.jazz
  compiler/tests/success/arm-m4/eor.jazz
  compiler/tests/success/arm-m4/intrinsic_adc.jazz
  compiler/tests/success/arm-m4/intrinsic_add.jazz
  compiler/tests/success/arm-m4/intrinsic_and.jazz
  compiler/tests/success/arm-m4/intrinsic_asr.jazz
  compiler/tests/success/arm-m4/intrinsic_bic.jazz
  compiler/tests/success/arm-m4/intrinsic_eor.jazz
  compiler/tests/success/arm-m4/intrinsic_ldr.jazz
  compiler/tests/success/arm-m4/intrinsic_ldrb.jazz
  compiler/tests/success/arm-m4/intrinsic_ldrh.jazz
  compiler/tests/success/arm-m4/intrinsic_ldrsb.jazz
  compiler/tests/success/arm-m4/intrinsic_ldrsh.jazz
  compiler/tests/success/arm-m4/intrinsic_lsl.jazz
  compiler/tests/success/arm-m4/intrinsic_lsr.jazz
  compiler/tests/success/arm-m4/intrinsic_mov.jazz
  compiler/tests/success/arm-m4/intrinsic_movt.jazz
  compiler/tests/success/arm-m4/intrinsic_mul.jazz
  compiler/tests/success/arm-m4/intrinsic_mvn.jazz
  compiler/tests/success/arm-m4/intrinsic_orr.jazz
  compiler/tests/success/arm-m4/intrinsic_ror.jazz
  compiler/tests/success/arm-m4/intrinsic_rsb.jazz
  compiler/tests/success/arm-m4/intrinsic_sbfx.jazz
  compiler/tests/success/arm-m4/intrinsic_sdiv.jazz
  compiler/tests/success/arm-m4/intrinsic_str.jazz
  compiler/tests/success/arm-m4/intrinsic_strb.jazz
  compiler/tests/success/arm-m4/intrinsic_strh.jazz
  compiler/tests/success/arm-m4/intrinsic_sub.jazz
  compiler/tests/success/arm-m4/intrinsic_tst.jazz
  compiler/tests/success/arm-m4/intrinsic_ubfx.jazz
  compiler/tests/success/arm-m4/intrinsic_udiv.jazz
  compiler/tests/success/arm-m4/intrinsic_umull.jazz
  compiler/tests/success/arm-m4/intrinsic_uxtb.jazz
  compiler/tests/success/arm-m4/intrinsic_uxth.jazz
  compiler/tests/success/arm-m4/ldr.jazz
  compiler/tests/success/arm-m4/ldrb.jazz
  compiler/tests/success/arm-m4/ldrh.jazz
  compiler/tests/success/arm-m4/ldrsb.jazz
  compiler/tests/success/arm-m4/ldrsh.jazz
  compiler/tests/success/arm-m4/lsl.jazz
  compiler/tests/success/arm-m4/lsr.jazz
  compiler/tests/success/arm-m4/mov.jazz
  compiler/tests/success/arm-m4/mul.jazz
  compiler/tests/success/arm-m4/mvn.jazz
  compiler/tests/success/arm-m4/orr.jazz
  compiler/tests/success/arm-m4/rol.jazz
  compiler/tests/success/arm-m4/ror.jazz
  compiler/tests/success/arm-m4/sdiv.jazz
  compiler/tests/success/arm-m4/str.jazz
  compiler/tests/success/arm-m4/strb.jazz
  compiler/tests/success/arm-m4/strh.jazz
  compiler/tests/success/arm-m4/sub.jazz
  compiler/tests/success/arm-m4/udiv.jazz
  eclib/JModel_m4.ec
  proofs/compiler/arm_instr_decl.v
Labels: bug, arm, EasyCrypt, semantics

#454 Do not use BatIO.to_input_channel
  compiler/src/parseio.ml
Labels: bug, ocaml

#462 Generalize find_map and use it in remove-globals
  proofs/compiler/remove_globals.v
  proofs/lang/utils.v
Labels: refactoring
