Repository jasmin-lang/jasmin, pull requests merged in 2023-07, with the labels that each got.

#493 Expose pretyping API needed by the language server
  compiler/src/pretyping.mli
Labels: ocaml

#514 Fix wsmul
  CHANGELOG.md
  proofs/compiler/arm_instr_decl.v
  proofs/lang/word.v
Labels: bug, semantics

#527 Regalloc: clearer error message
  compiler/src/regalloc.ml
  compiler/tests/fail/register_allocation/x86-64/bug_523.jazz
Labels: register-allocation

#528 Fix semantics of IMUL* instructions
  CHANGELOG.md
  eclib/JWord.ec
  proofs/compiler/x86_instr_decl.v
Labels: semantics

#492 ARM: rewrite semantics of SMMULR instruction
  CHANGELOG.md
  eclib/JModel_m4.ec
  proofs/compiler/arm_instr_decl.v
Labels: bug, arm

#531 Fix mulx
  CHANGELOG.md
  compiler/tests/success/x86-64/mulx.jazz
  eclib/JWord.ec
  proofs/compiler/x86_extra.v
  proofs/compiler/x86_instr_decl.v
  proofs/compiler/x86_params_proof.v
Labels: enhancement, semantics

#536 Pretyping.tt_prim: export & simplify
  compiler/src/pretyping.ml
  compiler/src/pretyping.mli
Labels: ocaml

#545 ARM: fix semantics of SMLAL
  CHANGELOG.md
  proofs/lang/word.v
Labels: bug, arm

#543 ARM: add instruction UMAAL
  CHANGELOG.md
  compiler/tests/success/arm-m4/intrinsic_umaal.jazz
  eclib/JModel_m4.ec
  proofs/compiler/arm_instr_decl.v
Labels: arm
