Repository jasmin-lang/jasmin, pull requests merged in 2024-10, with the labels that each got.

#918 eclib: add to_uintK_small, to_sintK_small, to_sintD_small, and to_sintB_small
  eclib/JWord.ec
Labels: EasyCrypt

#926 CI/coq-master: use elpi 1.20.0
  scripts/coq-elpi.nix
Labels: CI

#936 ARM: add instruction SBC
  CHANGELOG.md
  compiler/src/arm_arch_full.ml
  compiler/src/pp_arm_m4.ml
  compiler/tests/success/arm-m4/intrinsic_sbc.jazz
  eclib/JModel_m4.ec
  proofs/compiler/arm_instr_decl.v
  proofs/compiler/arm_instr_decl_lemmas.v
  proofs/compiler/arm_lowering.v
  proofs/compiler/arm_lowering_proof.v
Labels: arm

#911 Adding support for type definition
  CHANGELOG.md
  compiler/src/latex_printer.ml
  compiler/src/lexer.mll
  compiler/src/parser.mly
  compiler/src/pretyping.ml
  compiler/src/syntax.ml
  compiler/tests/fail/common/typealias_annotation_param.jazz
  compiler/tests/fail/common/typealias_arrayelement.jazz
  compiler/tests/fail/common/typealias_arrayelement_integer.jazz
  compiler/tests/fail/common/typealias_duplicate.jazz
  compiler/tests/fail/common/typealias_notfound.jazz
  compiler/tests/success/arm-m4/typealias_armv7.jazz
  compiler/tests/success/common/typealias.jazz
  compiler/tests/success/x86-64/typealias_amd64.jazz
Labels: feature request

#937 Do not use RAX to save the stack pointer on x86
  CHANGELOG.md
  compiler/tests/success/x86-64/bug_895.jazz
  proofs/compiler/x86_params.v
Labels: bug
