Repository jasmin-lang/jasmin, pull requests merged in 2024-12, with the labels that each got.

#985 Make _CoqProject compatible with ProofGeneral
  proofs/_CoqProject
Labels: bug

#973 fix ec semantics of shift operators
  CHANGELOG.md
  eclib/JWord.ec
Labels: bug, EasyCrypt

#992 CI: update nixpkgs
  .gitlab-ci.yml
  default.nix
  scripts/coq-elpi.nix
  scripts/nixpkgs.nix
Labels: CI

#986 latex_printer: do not print a blank line
  CHANGELOG.md
  compiler/src/latex_printer.ml
Labels: bug

#997 CI: disable the “cache dependencies” job
  .gitlab-ci.yml
Labels: CI

#971 Fix EC extraction in case on nested loops
  AUTHORS
  CHANGELOG.md
  compiler/src/toEC.ml
Labels: bug, EasyCrypt
