Repository jasmin-lang/jasmin, pull requests merged in 2024-07, with the labels that each got.

#859 toEC (leakage extraction): fix for loop bound swap
  CHANGELOG.md
  compiler/src/toEC.ml
Labels: bug, EasyCrypt

#867 ECLIB: remove deprecated "nosmt" tag
  eclib/JArray.ec
  eclib/JUtils.ec
  eclib/JWord.ec
Labels: EasyCrypt

#869 jasminc: remove deprecated -latex option
  CHANGELOG.md
  compiler/src/CLI_errors.ml
  compiler/src/glob_options.ml
  compiler/src/main_compiler.ml
Labels: ocaml
