Repository jasmin-lang/jasmin, pull requests merged in 2024-06, with the labels that each got.

#819 SCT checker: negative tests
  compiler/tests/sct-checker/fail/basic.jazz
  compiler/tests/sct-checker/fail/corruption.jazz
  compiler/tests/sct-checker/reject.expected
Labels: SCT checker

#807 Move Uint63 to its own library
  compiler/MANIFEST
  compiler/src/dune
  compiler/uint63/dune
  compiler/uint63/js/dune
  compiler/uint63/native/dune
  compiler/uint63/uint63.mli
  compiler/uint63/uint63_31.ml
  compiler/uint63/uint63_63.ml
Labels: ocaml

#814 Safety-checker: support for SLH primitives
  CHANGELOG.md
  compiler/safety/success/slh.jazz
  compiler/safetylib/safetyInterpreter.ml
Labels: safety-checking

#822 CI: update nixpkgs (to channel 24.05)
  scripts/nixpkgs.nix
Labels: CI

#813 Checksafety: minimal support of arrays in export functions
  compiler/safety/fail/array-export.jazz
  compiler/safety/success/array-export.jazz
  compiler/safetylib/domains/safetyPointsTo.ml
  compiler/safetylib/safetyAbsExpr.ml
Labels: safety-checking

#826 Use mathcomp 1.19.0
  scripts/mathcomp-word.nix
Labels: CI

#830 Register allocation: minor improvement
  compiler/src/regalloc.ml
Labels: register-allocation

#829 CI: add a coq-master job
  .gitlab-ci.yml
  default.nix
Labels: CI

#833 Raise lower bound on batteries in opam files
  compiler/jasmin.opam
  opam
Labels: opam

#848 stack alloc: truncation of stack variables
  CHANGELOG.md
  compiler/tests/success/x86-64/bug_681.jazz
  proofs/compiler/allocation_proof.v
  proofs/compiler/constant_prop_proof.v
  proofs/compiler/propagate_inline_proof.v
  proofs/compiler/stack_alloc.v
  proofs/compiler/stack_alloc_proof.v
  proofs/compiler/stack_alloc_proof_2.v
  proofs/lang/psem.v
  proofs/lang/values.v
Labels: bug

#844 Regalloc: improve liveness analysis
  compiler/src/liveness.ml
Labels: bug, register-allocation
