Repository jasmin-lang/jasmin, pull requests merged in 2025-03, with the labels that each got.

#1074 CI/coq-master: fix coq-elpi
  default.nix
  scripts/coq-elpi.nix
Labels: CI

#1075 Simplify proofs for SMTs
  compiler/examples/extraction-unit-tests/proofs.ec
  eclib/JByte_array.ec
  eclib/JMemory.ec
Labels: EasyCrypt

#1067 Adding a check to verify that functions names do not conflict when translated to assembly labels
  CHANGELOG.md
  compiler/src/label_check.ml
  compiler/src/label_check.mli
  compiler/src/main_compiler.ml
  compiler/tests/success/common/inline_label_duplication.jazz
Labels: bug

#1076 Test/compile-and-assemble: use a single program for all architectures
  compiler/config/tests.config
  compiler/scripts/check
  compiler/scripts/check-arm-m4
  compiler/scripts/check-risc-v
  default.nix
Labels: CI

#1081 Simplify proofs for SMTs
  eclib/JArray.ec
  eclib/JByte_array.ec
Labels: EasyCrypt

#1084 Simplify proofs for SMTs
  compiler/examples/extraction-unit-tests/proofs.ec
  eclib/JArray.ec
Labels: CI

#1089 fix default.nix
  default.nix
Labels: nix

#1088 Fix semantics of unsigned division
  CHANGELOG.md
  compiler/tests/exec/sem_unit.expected
  compiler/tests/exec/sem_unit.jazz
  compiler/tests/exec/sem_unit.ml
  proofs/compiler/arm_lowering_proof.v
  proofs/compiler/riscv_lowering_proof.v
  proofs/compiler/x86_lowering_proof.v
  proofs/lang/sem_op_typed.v
  proofs/lang/wsize.v
Labels: bug, semantics

#1091 ARM: fix semantics of the carry flag for LSR
  CHANGELOG.md
  eclib/JModel_m4.ec
  proofs/compiler/arm_instr_decl.v
Labels: bug, arm, semantics

#1090 Fix EC extraction of signed division
  CHANGELOG.md
  compiler/examples/extraction-unit-tests/.gitignore
  compiler/examples/extraction-unit-tests/Makefile
  compiler/examples/extraction-unit-tests/proofs.ec
  compiler/examples/extraction-unit-tests/sdiv.jazz
  eclib/JUtils.ec
  eclib/JWord.ec
Labels: bug, EasyCrypt

#1077 Use Coq 8.20
  default.nix
Labels: CI

#1096 Simplify proofs for SMTs
  eclib/JByte_array.ec
Labels: EasyCrypt

#1102 CI: use EasyCrypt 2025.03
  scripts/easycrypt.nix
Labels: CI, EasyCrypt

#1103 Checksafety: normalize often the list of if-conditions
  CHANGELOG.md
  compiler/safetylib/safetyPreanalysis.ml
Labels: bug, safety-checking
