Repository jasmin-lang/jasmin, pull requests merged in 2025-02, with the labels that each got.

#1027 Regalloc: improve printing of equiv. traces
  CHANGELOG.md
  compiler/src/regalloc.ml
Labels: register-allocation

#1032 EC: add unit tests for extraction
  .gitlab-ci.yml
  compiler/examples/extraction-unit-tests/.gitignore
  compiler/examples/extraction-unit-tests/Makefile
  compiler/examples/extraction-unit-tests/ec.config
  compiler/examples/extraction-unit-tests/loops.jazz
  compiler/examples/extraction-unit-tests/proofs.ec
Labels: EasyCrypt

#1015 updating printer `pp_iprog` function to print Cwhile Info
  CHANGELOG.md
  compiler/src/printer.ml
Labels: bug

#1045 Gimli proof: fix for latest EasyCrypt
  compiler/examples/gimli/proofs/gimliv.ec
Labels: EasyCrypt

#1028 Fixing type checking of function return storage type
  CHANGELOG.md
  compiler/src/latex_printer.ml
  compiler/src/pretyping.ml
  compiler/src/syntax.ml
  compiler/tests/fail/common/storage_signature_mismatch.jazz
  compiler/tests/success/common/bug_607.jazz
  compiler/tests/success/x86-64/test_ptr_fn_inline.jazz
Labels: bug, type-checking

#1044 Fix allocation of dead stack variables
  CHANGELOG.md
  compiler/src/intervalGraphColoring.ml
  compiler/src/varalloc.ml
  compiler/tests/fail/stack_allocation/x86-64/uninit_stack.jazz
  compiler/tests/success/x86-64/bug_680.jazz
Labels: bug, ocaml

#1048 Pretyping: remove dead code
  compiler/src/pretyping.ml
Labels: ocaml
