Repository jasmin-lang/jasmin, pull requests merged in 2025-04, with the labels that each got.

#1109 Checksafety: improve heuristic regarding “while” variables
  CHANGELOG.md
  compiler/safety/success/bug_1109.jazz
  compiler/safetylib/domains/safetyProduct.ml
  compiler/safetylib/safetyPreanalysis.ml
  compiler/safetylib/safetyPreanalysis.mli
Labels: safety-checking

#1113 CI/libjade: expose jasmin2ec
  scripts/test-libjade.sh
Labels: CI

#1114 jasminc: remove extraction to EC
  CHANGELOG.md
  compiler/src/CLI_errors.ml
  compiler/src/glob_options.ml
  compiler/src/main_compiler.ml
Labels: EasyCrypt

#1122 changing .globl to .global in pp_x86 for simplification
  compiler/src/pp_x86.ml
Labels: refactoring
