Repository jasmin-lang/jasmin, pull requests merged in 2025-01, with the labels that each got.

#1002 CI: update nixpkgs
  .gitlab-ci.yml
  scripts/nixpkgs.nix
Labels: CI

#1006 CI/coq-master: pin stdlib
  default.nix
Labels: CI

#995 use byte array in extraction
  CHANGELOG.md
  compiler/entry/jasmin2ec.ml
  compiler/examples/gimli/proofs/gimliv.ec
  compiler/src/toEC.ml
  compiler/src/toEC.mli
  compiler/tests/success/x86-64/array_cast.jazz
  eclib/JArray.ec
  eclib/JByte_array.ec
  eclib/JWord.ec
Labels: EasyCrypt

#1019 CI: update nixpkgs
  default.nix
  scripts/coq-elpi.nix
  scripts/easycrypt.nix
  scripts/nixpkgs.nix
Labels: CI

#1014 SCT checker: kill dead vars
  compiler/src/sct_checker_forward.ml
Labels: SCT checker

#1018 minor fix in JWord.ec
  eclib/JWord.ec
Labels: bug, EasyCrypt

#1021 Adding info to function
  CHANGELOG.md
  compiler/safetylib/safetyPreanalysis.ml
  compiler/src/conv.ml
  compiler/src/liveness.ml
  compiler/src/pretyping.ml
  compiler/src/prog.ml
  compiler/src/prog.mli
  compiler/src/ssa.ml
Labels: ocaml

#1025 Utils: remove dead functions
  compiler/src/utils.ml
  compiler/src/utils.mli
Labels: ocaml

#1031 Location: remove dead code
  compiler/src/location.ml
  compiler/src/location.mli
Labels: ocaml
